#!/usr/bin/env bash
#
# Set monitor brightness and colour temp according to sunrise and sunset.
#
# --- Dependencies ---
# sunwait, perl, ddcutil, grep and sed.
# Also you need to have the permissions of /dev/i2c-x devices set to rw as
# per ddcutil documentation.
#
# RGB values are calculated according to something like
# https://www.tannerhelland.com/4435/convert-temperature-rgb-algorithm-code/
# Call from cron every twenty minutes or so for a smooth transition.
# Monitors are automatically detected.
#
# eyesaver (C) 2019 A S Sharma
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

#### Get script location ####

SOURCE=${BASH_SOURCE[0]}
while [ -L "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
  SOURCE=$(readlink "$SOURCE")
  [[ $SOURCE != /* ]] && SOURCE=$DIR/$SOURCE # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )

#### Config file ####

known_variables="LAT LONG SMOOTHNESS FLOOR CEIL TEMP_FLOOR TEMP_CEIL RGB_SCALING CONTRAST DEBUG MAX_RETRIES"

source $DIR/read_config.sh $DIR/config "$known_variables"

#### End Config file ####

# test for dependencies
test -z $(which ddcutil) && echo "ddcutil needs to be installed"
test -z $(which jq) && echo "jq needs to be installed"
test -z $(which sunwait) && echo "sunwait needs to be installed"
test -z $(which perl) && echo "perl needs to be installed"


# get sunrise and sunset into bash string array
times=($(sunwait report ${LAT}N ${LONG}E | grep 'Civil twilight' | sed 's/://g' | grep -o -E '[0-9]+'))

# remove leading zeros so number not interpreted as octal
# and convert minutes into decimal
now=$((10#$(date +%H) * 100 + 10#$(date +%M) * 100 / 60))
sunrise=$((10#${times[0]}))
sunset=$((10#${times[1]}))

# brightness sigmoid function, then scale
brightness=$(perl -E "use Math::Trig; say (int((tanh(($now-$sunrise)/$SMOOTHNESS) - tanh(($now-$sunset)/$SMOOTHNESS)) / 2 * ($CEIL - $FLOOR) + $FLOOR))")

# similarly, color temperature
temp=$(perl -E "use Math::Trig; say (int((tanh(($now-$sunrise)/$SMOOTHNESS) - tanh(($now-$sunset)/$SMOOTHNESS)) / 2 * ($TEMP_CEIL - $TEMP_FLOOR) + $TEMP_FLOOR))")

# RGB values in [0, 255]
red=$(perl -E "use List::Util qw[min max]; say max(0, min(255, int($RGB_SCALING * (329.6987 * ($temp/100 - 60) ** -0.1332047592))))")
green=$(perl -E "use List::Util qw[min max]; say max(0, min(255, int($RGB_SCALING * (99.4708 * log($temp/100) - 161.119581))))")
blue=$(perl -E "use List::Util qw[min max]; say max(0, min(255, int($RGB_SCALING * (138.51773 * log($temp/100 - 10) - 305.0447927))))")

echo "Time is $(date +%H%M), sunrise is ${times[0]} and sunset is ${times[1]}."
echo "Setting brightness to $brightness."
echo "Setting colour temperature to $temp (RGB $red $green $blue)."

# detect monitors and get I2C bus number
for monitor in $(sudo ddcutil detect --terse | grep I2C | sed -e 's/.*-//'); do

    echo "Using i2c bus ${monitor}."

    sudo ddcutil -b ${monitor} setvcp 12 $CONTRAST
    sudo ddcutil -b ${monitor} setvcp 10 $brightness

    # unfortunately some take 0-100 and some 0-255 for RGB
    # so we must scale to monitor's native scale
    # Sometimes, the command fails, so retry a maximum of $MAX_RETRIES times.
    max=
    retries=0
    re='^[0-9]+$' # Regular expression to test if max is a number
    while [[ ! "$max" =~ $re ]] && [ "$retries" -lt "$MAX_RETRIES" ]
	do
	max=$(sudo ddcutil -b ${monitor} -t getvcp 16 | cut -d ' ' -f 5)

	if [[ ! "$max" =~ $re ]]
	then
	    echo Error: failed to get max from ddcutil. $retries/$MAX_RETRIES retries. >&2
	    retries=$((retries+1))

	    if [ "$retries" -eq "$MAX_RETRIES" ]
	    then
		echo Error: maximum retries \($MAX_RETRIES\) exceeded. Aborting. >&2
		exit 1
	    fi
	fi
    done

    # Set the target scaled rgb values
    red_scaled=$(($red * $max / 255))
    green_scaled=$(($green * $max / 255))
    blue_scaled=$(($blue * $max / 255))

    if [ "$DEBUG" = true ] ; then
	echo Now: $'\t'$now >&2
	echo Max: $'\t'$max >&2
	echo "Printing target values" >&2
	echo Red: $'\t'$red_scaled >&2
	echo Green: $'\t'$green_scaled >&2
	echo Blue: $'\t'$blue_scaled >&2
    fi

    # apply colour temperature
    sudo ddcutil --async -b ${monitor} setvcp 16 $(($red * $max / 255)) >&2
    sudo ddcutil --async -b ${monitor} setvcp 18 $(($green * $max / 255)) >&2
    sudo ddcutil --async -b ${monitor} setvcp 1a $(($blue * $max / 255)) >&2

    if [ "$DEBUG" = true ] ; then
	    # debugging / validation
	    echo "Printing debug info"
	    sudo ddcutil --async -b ${monitor} getvcp 10 >&2
	    sudo ddcutil --async -b ${monitor} getvcp 12 >&2
	    sudo ddcutil --async -b ${monitor} getvcp 16 >&2
	    sudo ddcutil --async -b ${monitor} getvcp 18 >&2
	    sudo ddcutil --async -b ${monitor} getvcp 1a >&2
    fi

done
